import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "../shared/styles/globals.css";
import {ReactNode} from "react";
import {Layout} from "@/shared/ui";
import {Header} from "@/widgets/header";

const nunito = Nunito({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-nunito",
    display: "swap",
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

type LayoutProps = Readonly<{
    children: ReactNode,
    modal: ReactNode,
}>

export default function RootLayout({ children, modal }: LayoutProps) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={nunito.variable} suppressHydrationWarning>
                <Layout>
                    <Header />
                    {children}
                    {modal}
                </Layout>
            </body>
        </html>
    )
}
